wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<title>/", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.update, name="update"),
    path("wiki/<title>/edit/", views.entry, name="edit"),
    path("random/", views.random, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from django import forms

class PageForm(forms.Form):
    title=forms.CharField(
        label="title", 
        max_length=50, 
        min_length=1, 
        error_messages = {'required': "Input a valid title"}
        )
    body=forms.CharField(
        label="body", 
        max_length=1000,
        min_length=10,
        error_messages = {'required': "Input a valid body"}
        )

class SubmitForm(forms.Form):
    value=forms.BooleanField(
        label="value"
    )

wiki/encyclopedia/views.py
import re
from random import randint
from pprint import pprint

from django.shortcuts import render, redirect
from markdown2 import Markdown

from . import util
from .forms import PageForm, SubmitForm

markdowner = Markdown()

def index(request):
    print(util.list_entries())
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    entry = util.get_entry(title)
    if entry:
        if request.method == "GET": # USE A FORM TO ELIMINATE "POST"
            pprint(request.GET)
            if request.GET.get('edit'):
                return render(request, "encyclopedia/entry.html", {
                    "title": title, 
                    "entry": entry,
                    "edit": True
                })
            else:
                return render(request, "encyclopedia/entry.html", {
                    "title": title,
                    "entry": markdowner.convert(entry)
                })  
    else:
        return render(request, "encyclopedia/error.html", {
            "title": title,
            "error_code": 404,
            "error_msg": "Requested Entry Not Found"
        })

def search(request):
    term = request.GET["term"]
    if term in util.list_entries():
        return redirect("encyclopedia:entry", title=term)
    else:
        results = []
        for entry in util.list_entries():
            if re.match(f".*{term.lower()}.*", entry.lower()):
                results.append(entry)
        
        return render(request, "encyclopedia/search_results.html", {"search_results": results})
    
def update(request):
    if request.method == "POST":
        context = {}
        form = PageForm(request.POST or None)
        context['form'] = form
        if form.is_valid():
            title=form.cleaned_data.get("title")
            body=form.cleaned_data.get("body")
            util.save_entry(title, body)
            request.method = "GET"
            return entry(request, title)
        else:
            return render(request, "encyclopedia/create_new_page.html")  
    elif request.method == "GET":
        return render(request, "encyclopedia/create_new_page.html") 

def random(request):
    entries =util.list_entries()
    title=entries[randint(0, len(entries)-1)]
    return entry(request, title)

wiki/encyclopedia/templates/encyclopedia/create_new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    New Page

{% endblock %}

{% block body %}
<form class="input" action="{% url 'encyclopedia:update' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input class="input" type="text" name="title" placeholder="Title"><br>
    <textarea placeholder="Enter details of your new entry in markdown format", name="body"></textarea><br>
    <input type="submit" value="Submit"></input>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %} 
    {% if edit %}
        <form action="{% url 'encyclopedia:update' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="title" value={{ title }}> 
            <textarea name="body">{{ entry }}</textarea>
            <input type="submit" value="Submit"></input>
        </form>
    {% else %}
        <ul>
            <li>{{ entry|safe }}</li>
        </ul>
        <form action="{% url 'encyclopedia:edit' title %}" method="get">
            {% csrf_token %}
            <input type="hidden" name="edit" value=True>
            <input type="submit" value="edit">
        </form>
    {% endif %}    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR {{ error_code }}
{% endblock %}

{% block body %}
    <h1>ERROR {{ error_code }} {{ error_msg }}</h1>

    <ul>
        <li>{{ title }}</li>
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form class="search" action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="term" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:update' %}" onclick="this.parentNode.submit()">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}" onclick="this.parentNode.submit()">
                        Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
<ul>
    {% if search_results %}
        {% for title in search_results %}
            <li><a href="/wiki/{{ title }}">{{ title }}</a></li>
        {% endfor %}
    {% else %}
        <p>No Results...</p>
    {% endif %}
{% endblock %}