OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/FIRST_DJANGO_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("HELLO_DJANGO.urls")),
    path('newyear/', include("NEWYEAR.urls")),
    path('tasks/', include("TODO_LIST.urls"))
]

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/HELLO_DJANGO/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("david", views.david, name="brian"),
    path("<str:name>", views.greet, name="greet")
]

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/NEWYEAR/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/TODO_LIST/urls.py
from django.urls import path
from . import views

app_name = "TODO_LIST"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/HELLO_DJANGO/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "HELLO_DJANGO/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def david(request):
    return HttpResponse("Hello, David!")

def greet(request, name):
    return render(request, "HELLO_DJANGO/greet.html", {
        "name": name.capitalize()
    })

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/NEWYEAR/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "NEWYEAR/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/TODO_LIST/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

tasks = ["foo", "bar", "baz"]

class NewTODOForm(forms.Form):
    task = forms.CharField(label="New TODO")

# Create your views here.
def index(request):

    # Check if there already exists a "tasks" key in our session

    if "tasks" not in request.session:

        # If not, create a new list
        request.session["tasks"] = []

    return render(request, "TODO_LIST/index.html", {
        "tasks": request.session["tasks"]
    })

# Add a new task:
def add(request):
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTODOForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            task = form.cleaned_data["task"]

            # Add the new task to our list of tasks
            request.session["tasks"] += [task]

            # Redirect user to list of tasks
            return HttpResponseRedirect(reverse("TODO_LIST:index"))
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "TODO_LIST/add.html", {
                "form": form
            })

    return render(request, "TODO_LIST/add.html", {
        "form": NewTODOForm()
    })

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/HELLO_DJANGO/templates/HELLO_DJANGO/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/HELLO_DJANGO/templates/HELLO_DJANGO/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
    </body>
</html>

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/NEWYEAR/templates/NEWYEAR/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="{% static 'NEWYEAR/styles.css' %}">
    <head>
        <title>Is it New Year's?</title>
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/TODO_LIST/templates/TODO_LIST/add.html
{% extends "TODO_LIST/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'TODO_LIST:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'TODO_LIST:index' %}">View Tasks</a>
{% endblock %}

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/TODO_LIST/templates/TODO_LIST/index.html
{% extends "TODO_LIST/layout.html" %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'TODO_LIST:add' %}">Add a New Task</a>
{% endblock %}

OLDSTUFF/wk3OLD/FIRST_DJANGO_PROJECT/TODO_LIST/templates/TODO_LIST/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>